import { Activity, AlertCircle, AlertTriangle, AlignLeft, BarChart2, Bell, BookOpen, Briefcase, Calendar, Camera, Check, CheckCircle, Clock, Code, Codepen, Coffee, Command, Copy, Crosshair, Database, DollarSign, Dribbble, Edit, Edit3, Facebook, File, FileMinus, FileText, Flag, Folder, Github, Globe, Headphones, Heart, Home, Info, Key, Layers, Link, Linkedin, List, Loader, Lock, Mail, Map, MapPin, Meh, MessageSquare, Minimize, Moon, MoreVertical, Octagon, Percent, Phone, PieChart, PlayCircle, Plus, Search, Send, Settings, Share2, ShoppingBag, ShoppingCart, Sliders, Smile, Star, Table, Tag, ThumbsUp, Trash, Trash2, TrendingDown, TrendingUp, Twitch, Twitter, User, UserCheck, UserPlus, Users, X, Youtube } from 'angular-feather/icons';

import { CommonModule } from '@angular/common';
import { FeatherModule } from 'angular-feather';
import { NgModule } from '@angular/core';

// Select some icons (use an object, not an array)
const icons = {
    Camera,
    Heart,
    Lock,
    Table,
    Send,
    Activity,
    ThumbsUp,
    Edit,
    Github,
    AlignLeft,
    AlertTriangle,
    FileMinus,
    Crosshair,
    Twitch,
    Plus,
    Youtube,
    File,
    Folder,
    Trash,
    Link,
    Meh,
    Facebook,
    Twitter,
    UserPlus,
    Codepen,
    Smile,
    Settings,
    Linkedin,
    Dribbble,
    X,
    ShoppingBag,
    Octagon,
    MapPin,
    Command,
    FileText,
    Copy,
    Flag,
    List,
    Share2,
    PlayCircle,
    UserCheck,
    BookOpen,
    Key,
    Search,
    Check,
    Coffee,
    Code,
    Star,
    Headphones,
    Moon,
    Briefcase,
    MessageSquare,
    Users,
    Map,
    BarChart2,
    Info,
    Calendar,
    Loader,
    AlertCircle,
    MoreVertical,
    Minimize,
    Bell,
    Phone,
    Edit3,
    Clock,
    Tag,
    Globe,
    Trash2,
    DollarSign,
    Percent,
    Database,
    CheckCircle,
    ShoppingCart,
    Sliders,
    Layers,
    User,
    Mail,
    PieChart,
    Home,
    TrendingUp,
    TrendingDown
};

@NgModule({
    declarations: [],
    imports: [
        CommonModule,
        FeatherModule.pick(icons)
    ],
    exports: [
        FeatherModule
    ]
})
export class FeathericonsModule { }